### ISSUE TITLE
本地运行显示Loading remote code failed: model, No module named 'model'

### ISSUE THREAD

**Issue by zjkaaap** [HG-ha/SenseVoice-Api#1]
具体报错：
You are using the latest version of funasr-1.1.0
Loading remote code failed: model, No module named 'model'
Traceback (most recent call last):
  File "/home/zjk/SenseVoice-Api/main.py", line 23, in <module>
    model = AutoModel(
  File "/home/zjk/anaconda3/envs/paddlespeech/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/home/zjk/anaconda3/envs/paddlespeech/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 245, in build_model
    model.to(device)
  File "/home/zjk/anaconda3/envs/paddlespeech/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1137, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
TypeError: to() received an invalid combination of arguments - got (list), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format memory_format)

**Comment by HG-ha** [comment]
修改device为"cpu"或"cuda:0"即可
